server:
    port: 6001
    tomcat:
        uri-encoding: UTF-8
  #应用名称
spring:
    dubbo:
      application:
        name: outer-consumer
  #注册中心地址
      protocol:
        name: dubbo
      registry:
        address: zookeeper://127.0.0.1:2161
  #调用dubbo组建扫描的项目路径
      scan: com.outer.controller
  #telnet端口
      qos:
        port: 22223
  #检查服务是否可用默认为true，不可用时抛出异常，阻止spring初始化，为方便部署，可以改成false
      consumer:
        check: false
        timeout: 300000